
# Docker image with Python and Docker pre-installed
image: gitpod/workspace-python-3.12

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: echo 'start script'
  - name: Setup Environment
    init: |            
      npm install -g @anthropic/claude-code   
      echo "Claude Code installed. Run 'claude' to start."
    command: |
      # Start Claude Code automatically
      echo "Starting Claude Code..."
      claude

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

 