# Use the custom Dockerfile for the workspace image
image:
  file: .gitpod.Dockerfile

# Define the tasks to be run in the terminal
tasks:
  - name: Build and Start     
    init: |
      echo "[*] Installing Claude CLI..."
      npm install -g @anthropic-ai/claude-code
      echo "Initialization complete."
    command: echo "Starting server..."      

# Set up VS Code extensions for each language
vscode:
  extensions:
    # Python language support
    - ms-python.python
    # Node.js and TypeScript support
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - ms-vscode.vscode-typescript-next
    # Scala language support
    - scala-lang.scala
    

# Open specific ports for the server and other services
ports:
  - port: 25565 # Standard Minecraft port
    onOpen: ignore
  - port: 8080 # Example web server port
    onOpen: ignore

# Customize editor settings, e.g., the default terminal
# gitpod.workspaceSettings:
#   terminal.integrated.shell.linux: /bin/bash
